// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/all_areas": {
            "get": {
                "description": "GetAllAreas is a handler to get a slice of record(s)from device info table in database",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "矿工页"
                ],
                "summary": "获取所有的地区列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errors.GenericError"
                        }
                    }
                }
            }
        },
        "/create_application": {
            "post": {
                "description": "GetDeviceInfoHandler is a function to create an application for activation code",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "申请激活码"
                ],
                "summary": "申请激活码",
                "parameters": [
                    {
                        "description": "请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Application"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.JsonObject"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errors.GenericError"
                        }
                    }
                }
            }
        },
        "/device_binding": {
            "get": {
                "description": "DeviceBindingHandler is a function to create an application for activation code",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "控制台"
                ],
                "summary": "设备绑定",
                "parameters": [
                    {
                        "type": "string",
                        "description": "设备ID",
                        "name": "device_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "用户ID",
                        "name": "user_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.JsonObject"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errors.GenericError"
                        }
                    }
                }
            }
        },
        "/get_applications": {
            "get": {
                "description": "GetApplicationsHandler is a function to get a slice of record(s) from application table in database",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "申请激活码"
                ],
                "summary": "获取申请激活码记录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户ID",
                        "name": "user_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "分页页码，默认 1",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "分页页数 默认 50",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "ASC",
                            "DESC"
                        ],
                        "type": "string",
                        "description": "排序， Enums(ASC, DESC)",
                        "name": "order",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "排序字段",
                        "name": "order_field",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.JsonObject"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "list": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/model.Application"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errors.GenericError"
                        }
                    }
                }
            }
        },
        "/get_cache_list": {
            "get": {
                "description": "GetDeviceInfoHandler is a handler to get a slice of record(s) from CacheEvent table in database",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "矿工页"
                ],
                "summary": "获取设备的缓存列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "设备ID",
                        "name": "device_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "分页页码，默认 1",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "分页页数 默认 50",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "ASC",
                            "DESC"
                        ],
                        "type": "string",
                        "description": "排序， Enums(ASC, DESC)",
                        "name": "order",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "排序字段",
                        "name": "order_field",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.JsonObject"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "list": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/model.CacheEvent"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errors.GenericError"
                        }
                    }
                }
            }
        },
        "/get_device_info": {
            "get": {
                "description": "GetDeviceInfoHandler is a handler to get a slice of record(s) from device info table in database",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "矿工页"
                ],
                "summary": "获取矿工页列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户ID",
                        "name": "user_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "设备ID",
                        "name": "device_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "国家地区",
                        "name": "ip_location",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "节点类型，默认全部",
                        "name": "node_type",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "分页页码，默认 1",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "分页页数 默认 50",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "ASC",
                            "DESC"
                        ],
                        "type": "string",
                        "description": "排序， Enums(ASC, DESC)",
                        "name": "order",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "排序字段",
                        "name": "order_field",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.JsonObject"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "list": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/model.DeviceInfo"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errors.GenericError"
                        }
                    }
                }
            }
        },
        "/get_diagnosis_days": {
            "get": {
                "description": "GetDeviceDiagnosisDailyHandler is a function to get a slice of record(s) from device info daily diagnosis",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "矿工页"
                ],
                "summary": "获取历史数据诊断",
                "parameters": [
                    {
                        "type": "string",
                        "description": "设备ID",
                        "name": "device_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "开始时间",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "结束时间",
                        "name": "to",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.JsonObject"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "series_data": {
                                            "$ref": "#/definitions/dao.DeviceStatistics"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errors.GenericError"
                        }
                    }
                }
            }
        },
        "/get_diagnosis_hours": {
            "get": {
                "description": "GetDeviceDiagnosisHourHandler is a function to get a slice of record(s) from device info hourly diagnosis",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "矿工页"
                ],
                "summary": "获取实时监控",
                "parameters": [
                    {
                        "type": "string",
                        "description": "设备ID",
                        "name": "device_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "开始时间",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "结束时间",
                        "name": "to",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.JsonObject"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "series_data": {
                                            "$ref": "#/definitions/dao.DeviceStatistics"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errors.GenericError"
                        }
                    }
                }
            }
        },
        "/get_index_info": {
            "get": {
                "description": "GetIndexInfoHandler is a function to get a single record from the full node info table in the redis",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "首页"
                ],
                "summary": "获取数据总览数据",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.FullNodeInfo"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errors.GenericError"
                        }
                    }
                }
            }
        },
        "/get_map_info": {
            "get": {
                "description": "GetMapInfoHandler is a function to get a slice of record(s) from devices map",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "首页"
                ],
                "summary": "获取地图信息接口",
                "parameters": [
                    {
                        "type": "string",
                        "description": "设备ID",
                        "name": "device_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "状态",
                        "name": "device_status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "页数",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "ASC",
                            "DESC"
                        ],
                        "type": "string",
                        "description": "排序， Enums(ASC, DESC)",
                        "name": "order",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "排序字段",
                        "name": "order_field",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.JsonObject"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        " total": {
                                            "type": "number"
                                        },
                                        "list": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/api.MapReturnForSwag"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errors.GenericError"
                        }
                    }
                }
            }
        },
        "/get_retrieval_list": {
            "get": {
                "description": "GetRetrievalListHandler is a handler to get a slice of record(s) from RetrievalEvent table in database",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "矿工页"
                ],
                "summary": "获取检索数据列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "设备ID",
                        "name": "device_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "分页页码，默认 1",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "分页页数 默认 50",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "ASC",
                            "DESC"
                        ],
                        "type": "string",
                        "description": "排序， Enums(ASC, DESC)",
                        "name": "order",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "排序字段",
                        "name": "order_field",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.JsonObject"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "list": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/model.RetrievalEvent"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errors.GenericError"
                        }
                    }
                }
            }
        },
        "/get_user_device_profile": {
            "get": {
                "description": "DeviceBindingHandler is a function to get user devices overview",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "控制台"
                ],
                "summary": "用户总览",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户ID",
                        "name": "user_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.JsonObject"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "profile": {
                                            "$ref": "#/definitions/dao.UserDeviceProfile"
                                        },
                                        "series_data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/dao.DeviceStatistics"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errors.GenericError"
                        }
                    }
                }
            }
        },
        "/get_validation_list": {
            "get": {
                "description": "GetValidationListHandler is a handler to get a slice of record(s) from ValidationEvent table in database",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "矿工页"
                ],
                "summary": "获取验证数据列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "设备ID",
                        "name": "device_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "分页页码，默认 1",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "分页页数 默认 50",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "ASC",
                            "DESC"
                        ],
                        "type": "string",
                        "description": "排序， Enums(ASC, DESC)",
                        "name": "order",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "排序字段",
                        "name": "order_field",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.JsonObject"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "list": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/model.ValidationEvent"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errors.GenericError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.JsonObject": {
            "type": "object",
            "additionalProperties": true
        },
        "api.MapReturnForSwag": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "value": {
                    "type": "array",
                    "items": {
                        "type": "number"
                    }
                }
            }
        },
        "dao.DeviceStatistics": {
            "type": "object",
            "properties": {
                "date": {
                    "description": "日期",
                    "type": "string"
                },
                "disk_usage": {
                    "description": "磁盘使用率",
                    "type": "number"
                },
                "downstream_traffic": {
                    "description": "下行流量",
                    "type": "number"
                },
                "income": {
                    "description": "收益",
                    "type": "number"
                },
                "latency": {
                    "description": "时延",
                    "type": "number"
                },
                "nat_ratio": {
                    "description": "NAT率",
                    "type": "number"
                },
                "online_time": {
                    "description": "在线时长",
                    "type": "number"
                },
                "pkg_loss_ratio": {
                    "description": "丢包率",
                    "type": "number"
                },
                "retrieval_count": {
                    "description": "检索数量",
                    "type": "number"
                },
                "upstream_traffic": {
                    "description": "上行流量",
                    "type": "number"
                }
            }
        },
        "dao.UserDeviceProfile": {
            "type": "object",
            "properties": {
                "abnormal_num": {
                    "description": "设备异常",
                    "type": "integer"
                },
                "cumulative_profit": {
                    "description": "累计收益",
                    "type": "number"
                },
                "month_profit": {
                    "description": "近30天收益",
                    "type": "number"
                },
                "offline_num": {
                    "description": "设备离线",
                    "type": "integer"
                },
                "online_num": {
                    "description": "在线设备数",
                    "type": "integer"
                },
                "seven_days_profit": {
                    "description": "近7天收益",
                    "type": "number"
                },
                "today_profit": {
                    "description": "今日收益",
                    "type": "number"
                },
                "total_bandwidth": {
                    "description": "总上行速度",
                    "type": "number"
                },
                "total_num": {
                    "description": "设备总数",
                    "type": "integer"
                },
                "yesterday_profit": {
                    "description": "昨日收益",
                    "type": "number"
                }
            }
        },
        "errors.GenericError": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "err": {}
            }
        },
        "model.Application": {
            "type": "object",
            "properties": {
                "amount": {
                    "description": "数量",
                    "type": "integer"
                },
                "area_id": {
                    "description": "国家地区ID，格式：CN-GD-Shenzhen",
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "disk_space": {
                    "description": "存储空间",
                    "type": "number"
                },
                "email": {
                    "description": "邮箱地址",
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "ip": {
                    "description": "IP地址",
                    "type": "string"
                },
                "ip_city": {
                    "description": "城市（弃用）",
                    "type": "string"
                },
                "ip_country": {
                    "description": "国家（弃用）",
                    "type": "string"
                },
                "node_type": {
                    "description": "节点类型",
                    "type": "integer"
                },
                "status": {
                    "description": "状态",
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                },
                "upstream_bandwidth": {
                    "description": "上行带宽",
                    "type": "number"
                },
                "user_id": {
                    "description": "用户ID",
                    "type": "string"
                }
            }
        },
        "model.CacheEvent": {
            "type": "object",
            "properties": {
                "block_size": {
                    "description": "文件大小",
                    "type": "number"
                },
                "blocks": {
                    "description": "blocks",
                    "type": "integer"
                },
                "carfile_cid": {
                    "description": "CID",
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "device_id": {
                    "description": "设备ID",
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "time": {
                    "description": "时间",
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "model.DeviceInfo": {
            "type": "object",
            "properties": {
                "active_status": {
                    "description": "激活状态",
                    "type": "integer"
                },
                "bandwidth_down": {
                    "description": "下行带宽",
                    "type": "number"
                },
                "bandwidth_up": {
                    "description": "上行带宽",
                    "type": "number"
                },
                "bind_status": {
                    "description": "绑定状态",
                    "type": "string"
                },
                "block_count": {
                    "description": "blocks",
                    "type": "integer"
                },
                "bound_at": {
                    "description": "绑定时间",
                    "type": "string"
                },
                "cpu_cores": {
                    "description": "CPU核数",
                    "type": "integer"
                },
                "cpu_usage": {
                    "description": "CPU使用率",
                    "type": "number"
                },
                "created_at": {
                    "type": "string"
                },
                "cumulative_profit": {
                    "description": "总收益",
                    "type": "number"
                },
                "deleted_at": {
                    "type": "string"
                },
                "device_id": {
                    "description": "设备ID",
                    "type": "string"
                },
                "device_name": {
                    "description": "设备名称",
                    "type": "string"
                },
                "device_rank": {
                    "description": "排名",
                    "type": "integer"
                },
                "device_status": {
                    "description": "设备状态",
                    "type": "string"
                },
                "disk_space": {
                    "description": "磁盘大小",
                    "type": "number"
                },
                "disk_type": {
                    "description": "磁盘类型",
                    "type": "string"
                },
                "disk_usage": {
                    "description": "磁盘使用率",
                    "type": "number"
                },
                "download_count": {
                    "description": "检索次数",
                    "type": "integer"
                },
                "external_ip": {
                    "description": "外网IP",
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "internal_ip": {
                    "description": "内网IP",
                    "type": "string"
                },
                "io_system": {
                    "description": "文件系统",
                    "type": "string"
                },
                "ip_city": {
                    "description": "城市",
                    "type": "string"
                },
                "ip_country": {
                    "description": "国家",
                    "type": "string"
                },
                "ip_location": {
                    "description": "国家地区",
                    "type": "string"
                },
                "ip_province": {
                    "description": "省",
                    "type": "string"
                },
                "latency": {
                    "description": "线路时延",
                    "type": "number"
                },
                "latitude": {
                    "description": "纬度",
                    "type": "number"
                },
                "longitude": {
                    "description": "经度",
                    "type": "number"
                },
                "mac_location": {
                    "description": "mac地址",
                    "type": "string"
                },
                "memory": {
                    "description": "内存",
                    "type": "number"
                },
                "memory_usage": {
                    "description": "内存使用率",
                    "type": "number"
                },
                "month_profit": {
                    "description": "月收益",
                    "type": "number"
                },
                "nat_ratio": {
                    "description": "NAT率",
                    "type": "number"
                },
                "nat_type": {
                    "description": "NAT 类型",
                    "type": "string"
                },
                "network_info": {
                    "description": "网络信息",
                    "type": "string"
                },
                "network_type": {
                    "description": "网络类型",
                    "type": "string"
                },
                "node_type": {
                    "description": "类型",
                    "type": "integer"
                },
                "online_time": {
                    "description": "在线时长",
                    "type": "number"
                },
                "operator": {
                    "description": "操作系统",
                    "type": "string"
                },
                "pkg_loss_ratio": {
                    "description": "丢包率",
                    "type": "number"
                },
                "product_type": {
                    "description": "产品类型",
                    "type": "string"
                },
                "scheduler_id": {
                    "description": "schedulerID",
                    "type": "string"
                },
                "seven_days_profit": {
                    "description": "七天收益",
                    "type": "number"
                },
                "sn_code": {
                    "description": "sn码",
                    "type": "string"
                },
                "system_version": {
                    "description": "版本",
                    "type": "string"
                },
                "today_online_time": {
                    "description": "今日在线时长",
                    "type": "number"
                },
                "today_profit": {
                    "description": "今日收益",
                    "type": "number"
                },
                "total_download": {
                    "description": "总下行流量",
                    "type": "number"
                },
                "total_upload": {
                    "description": "总上行流量",
                    "type": "number"
                },
                "updated_at": {
                    "type": "string"
                },
                "upnp": {
                    "description": "UPNP",
                    "type": "string"
                },
                "user_id": {
                    "description": "用户ID（钱包地址）",
                    "type": "string"
                },
                "work_status": {
                    "description": "设备诊断状态",
                    "type": "string"
                },
                "yesterday_profit": {
                    "description": "昨日收益",
                    "type": "number"
                }
            }
        },
        "model.FullNodeInfo": {
            "type": "object",
            "properties": {
                "candidate_count": {
                    "description": "L1 候选节点",
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "edge_count": {
                    "description": "L2 边缘节点",
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "next_election_time": {
                    "description": "下一轮选举时间",
                    "type": "string"
                },
                "retrieval_count": {
                    "description": "加速次数",
                    "type": "integer"
                },
                "time": {
                    "type": "string"
                },
                "total_carfile": {
                    "description": "已加速Carflie",
                    "type": "integer"
                },
                "total_carfile_size": {
                    "description": "已加速Carflie大小",
                    "type": "number"
                },
                "total_downstream_bandwidth": {
                    "description": "下载带宽",
                    "type": "number"
                },
                "total_node_count": {
                    "description": "全球分布式节点数量",
                    "type": "integer"
                },
                "total_storage": {
                    "description": "存储容量",
                    "type": "number"
                },
                "total_upstream_bandwidth": {
                    "description": "上行带宽",
                    "type": "number"
                },
                "updated_at": {
                    "type": "string"
                },
                "validator_count": {
                    "description": "L1 验证节点",
                    "type": "integer"
                }
            }
        },
        "model.RetrievalEvent": {
            "type": "object",
            "properties": {
                "blocks": {
                    "description": "blocks",
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "device_id": {
                    "description": "设备ID",
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "time": {
                    "description": "时间",
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "upstream_bandwidth": {
                    "description": "上传流量",
                    "type": "number"
                }
            }
        },
        "model.ValidationEvent": {
            "type": "object",
            "properties": {
                "blocks": {
                    "description": "blocks",
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "device_id": {
                    "description": "设备ID",
                    "type": "string"
                },
                "duration": {
                    "description": "完成时长",
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "status": {
                    "description": "状态",
                    "type": "integer"
                },
                "time": {
                    "description": "时间",
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "upstream_traffic": {
                    "description": "上传流量",
                    "type": "number"
                },
                "validator_id": {
                    "description": "验证人",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
